# Generated by Django 3.2.6 on 2021-09-10 10:40

import ckeditor.fields
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'User',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='card',
            fields=[
                ('card_name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('project_card', models.CharField(max_length=100, unique=True)),
                ('start_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('is_complete', models.BooleanField(default=False)),
                ('color', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'card',
            },
        ),
        migrations.CreateModel(
            name='checklist',
            fields=[
                ('checklist', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('is_complete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'checklist',
            },
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('project_name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('wiki', ckeditor.fields.RichTextField()),
                ('is_complete', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='project', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='lists',
            fields=[
                ('list_name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('color', models.CharField(max_length=50)),
                ('project_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker_app.project')),
            ],
            options={
                'db_table': 'lists',
            },
        ),
        migrations.CreateModel(
            name='card_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker_app.card')),
            ],
            options={
                'db_table': 'card_comment',
            },
        ),
        migrations.AddField(
            model_name='card',
            name='asignee_checklist',
            field=models.ManyToManyField(to='tracker_app.checklist'),
        ),
        migrations.AddField(
            model_name='card',
            name='assignee',
            field=models.ManyToManyField(related_name='card', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='card',
            name='list_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker_app.lists'),
        ),
    ]
