# Generated by Django 3.2.6 on 2021-09-10 15:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='asignee_checklist',
            field=models.ManyToManyField(blank=True, to='tracker_app.checklist'),
        ),
        migrations.AlterField(
            model_name='card',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 10, 15, 29, 16, 839478)),
        ),
        migrations.AlterField(
            model_name='card',
            name='project_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker_app.project'),
        ),
        migrations.AlterField(
            model_name='card',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 10, 15, 29, 16, 839450)),
        ),
    ]
