# Generated by Django 3.2.6 on 2021-09-11 06:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0002_auto_20210910_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 11, 6, 11, 27, 140962)),
        ),
        migrations.AlterField(
            model_name='card',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 11, 6, 11, 27, 140936)),
        ),
        migrations.AlterField(
            model_name='lists',
            name='project_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_lists', to='tracker_app.project'),
        ),
    ]
