# Generated by Django 3.2.6 on 2021-09-11 07:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0003_auto_20210911_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 11, 7, 5, 30, 627318)),
        ),
        migrations.AlterField(
            model_name='card',
            name='list_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_cards', to='tracker_app.lists'),
        ),
        migrations.AlterField(
            model_name='card',
            name='project_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_cards', to='tracker_app.project'),
        ),
        migrations.AlterField(
            model_name='card',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 11, 7, 5, 30, 627295)),
        ),
    ]
