# Generated by Django 3.2.6 on 2021-09-11 07:07

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0004_auto_20210911_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='assignee',
            field=models.ManyToManyField(related_name='assignee_card', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='card',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 11, 7, 7, 25, 264730)),
        ),
        migrations.AlterField(
            model_name='card',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 11, 7, 7, 25, 264706)),
        ),
    ]
